// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdAywMOU4rnZ3V7B5Ec--GihNOyZod_ps',
    appId: '1:894137056148:web:d0c54c83df23ee2a2cad81',
    messagingSenderId: '894137056148',
    projectId: 'bank-ease',
    authDomain: 'bank-ease.firebaseapp.com',
    storageBucket: 'bank-ease.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrWC4j9d28zKoyeqYg_LsqAXUb0BWOSSM',
    appId: '1:894137056148:android:1997d4d3dc1083a32cad81',
    messagingSenderId: '894137056148',
    projectId: 'bank-ease',
    storageBucket: 'bank-ease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmNm0VLnJVmpXRcM1hNJF-ynrK9xK7az0',
    appId: '1:894137056148:ios:efc417f29bb2e4522cad81',
    messagingSenderId: '894137056148',
    projectId: 'bank-ease',
    storageBucket: 'bank-ease.appspot.com',
    iosBundleId: 'com.example.bankEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmNm0VLnJVmpXRcM1hNJF-ynrK9xK7az0',
    appId: '1:894137056148:ios:efc417f29bb2e4522cad81',
    messagingSenderId: '894137056148',
    projectId: 'bank-ease',
    storageBucket: 'bank-ease.appspot.com',
    iosBundleId: 'com.example.bankEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdAywMOU4rnZ3V7B5Ec--GihNOyZod_ps',
    appId: '1:894137056148:web:639c8b3b25d2437d2cad81',
    messagingSenderId: '894137056148',
    projectId: 'bank-ease',
    authDomain: 'bank-ease.firebaseapp.com',
    storageBucket: 'bank-ease.appspot.com',
  );
}
